// This file will be generated by running:
// npx supabase gen types typescript --project-id <your-project-id> > types/database.types.ts
//
// For now, we use the types defined in types/index.ts
// After generating, you can import from this file instead

export type { Database } from './index';



